// Type-safe wrappers around @crawsecure/browser.
// All analysis is local — no file content is sent anywhere.

import type { Finding, ScanResult } from "@/types/scanner";

/**
 * Runs the browser scan engine on a FileList.
 * The engine is dynamically imported so it's only loaded client-side
 * (FileReader is browser-only).
 */
export async function runBrowserScan(fileList: FileList | File[]): Promise<ScanResult> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { scanBrowserFiles } = await import("@crawsecure/browser") as any;

  const raw = await scanBrowserFiles(fileList);

  return {
    source:         "browser",
    findings:       raw.findings       as Finding[],
    score:          raw.score          as number,
    risk:           raw.risk,
    summary:        raw.summary,
    rulesTriggered: raw.rulesTriggered as string[],
    filesScanned:   raw.filesScanned   as number,
  };
}

/**
 * Parses a crawsecure.json file generated by the CLI.
 * Supports both v1.x and v2.0 formats.
 */
export function parseCrawsecureJson(text: string): ScanResult {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const json: any = JSON.parse(text);
  const summary   = json.summary ?? {};

  return {
    source:         "json",
    findings:       (json.findings ?? []) as Finding[],
    score:          summary.score         ?? json.score ?? 0,
    risk:           summary.risk          ?? json.risk  ?? "SAFE",
    summary: {
      critical: summary.critical ?? 0,
      warning:  summary.warning  ?? 0,
      info:     summary.info     ?? 0,
    },
    rulesTriggered: json.rulesTriggered ?? [],
    filesScanned:   summary.filesScanned ?? json.filesScanned ?? 0,
    generatedAt:    json.generatedAt,
  };
}

/**
 * Triggers a browser download of crawsecure.json.
 * Generated entirely client-side — never uploaded.
 */
export async function exportScanJSON(result: ScanResult): Promise<void> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { buildOutputJSON } = await import("@crawsecure/browser") as any;
  const payload = buildOutputJSON(result);
  const blob    = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
  const url     = URL.createObjectURL(blob);
  const a       = document.createElement("a");
  a.href        = url;
  a.download    = "crawsecure.json";
  a.click();
  URL.revokeObjectURL(url);
}
