import type { Metadata } from "next";
import { Badge } from "@/components/ui/badge";

export const metadata: Metadata = {
  title: "Analyze",
  description: "Scan a ClawHub skill locally. Your code never leaves your machine.",
};

// Scanner UI is built in Step 3 (FileDropzone + BrowserScanner).
// This shell sets up the page structure and trust context.

export default function AnalyzePage() {
  return (
    <div className="flex flex-col items-center gap-8 py-8">

      {/* Header */}
      <div className="text-center max-w-xl">
        <h1 className="text-2xl font-semibold mb-2">Skill Security Scanner</h1>
        <p className="text-muted-foreground text-sm">
          Load a{" "}
          <code className="bg-muted px-1 rounded text-xs">crawsecure.json</code>{" "}
          generated by the CLI, or drop your skill directory files below.
          Analysis runs entirely in your browser.
        </p>
      </div>

      {/* Trust pill */}
      <div className="flex items-center gap-2 text-xs text-muted-foreground bg-muted/60 px-4 py-2 rounded-full border">
        <span className="text-green-500">●</span>
        <span>Your files never leave this device</span>
        <Badge variant="outline" className="text-[10px] h-4 px-1.5">Offline</Badge>
      </div>

      {/* Drop zone placeholder — replaced by FileDropzone in Step 3 */}
      <div className="w-full max-w-xl border-2 border-dashed border-border rounded-xl p-16 flex flex-col items-center gap-3 text-center text-muted-foreground cursor-pointer hover:border-violet-400 hover:bg-muted/30 transition-colors">
        <span className="text-4xl">📂</span>
        <p className="text-sm font-medium">Drop crawsecure.json here</p>
        <p className="text-xs">or click to browse</p>
        <p className="text-xs mt-2 opacity-60">Scanner coming in Step 3</p>
      </div>

    </div>
  );
}
